import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable()
export class UniversidadesProvider {

  constructor(public http: HttpClient) {
    console.log('Hello UniversidadesProvider Provider');
  }

  getUniversidades() {
    return new Promise<Array<any>>((resolve, reject) => {
      setTimeout(() => {
        resolve([
          "Actuaria(Ciencias Actuariales) (Ingeniería Matemáticas M/Economía",
          "Antropología Física",
          "Antropología Social",
          "Arqueología",
          "Arquitectura(Arquitectura de Proyectos",
          "Arquitectura del Paisaje(Licenciatura en Diseño Paisajista",
          "Asistente Judicial(Procurador) (Técnico Jurídico",
          "Asistente Odontológico(Técnico en Odontología",
          "Astronomía",
          "Auxiliar de Enfermería(Técnico en Enfermería) (Asistente de Enfermería)(Diplomado en Enfermería",
          "Bibliotecología",
          "Bioingeniería",
          "Biología Marina",
          "Biotecnología(Ingeniería Biológica)(Ingeniería en Biotecnología",
          "Camarógrafos y Fotógrafos",
          "Ciencias Biológicas",
          "Ciencias Criminalísticas(Licenciatura en Criminología",
          "Ciencias de la Educación",
          "Ciencia de los Materiales(Ingeniería de Materiales",
          "Ciencias Estadísticas",
          "Ciencias Filosóficas (Licenciatura en Filosofía",
          "Ciencias Físicas (Licenciatura en Física",
          "Ciencias Geofísicas(Licenciatura en Ciencias Geofísicas",
          "Ciencias Matemáticas",
          "Ciencias Políticas",
          "Ciencias Químicas",
          "Cine, TV y Video",
          "Cirugía Plástica (Especialidad de Medicina",
          "Comercio Internacional (Comercio Exterior) (Negocios Internacionales) (Administración en Comercio Internacional",
          "Comunicación Audiovisual",
          "Contabilidad y Auditoría(Contador Público)(Contaduría Pública",
          "Coreografía",
          "Danza",
          "Derecho",
          "Dibujo Técnico (Dibujo Arquitectónico) (Dibujo Mecánico) (Dibujo Estructural",
          "Dirección y Producción de Eventos(Producción de Eventos",
          "Diseño de Ambientes Interiores(Diseño de Interiores) (Arquitectura de Interiores",
          "Diseño de Vestuario y Textil(Diseño de Moda",
          "Diseño Digital(Licenciatura en Animación y Efectos Visuales) (Animación Digital) (Arte Digital",
          "Diseño Gráfico(Diseño de la Comunicación Gráfica)(Comunicación Gráfica",
          "Diseño Industrial",
          "Diseño Teatral",
          "Ecología",
          "Economía",
          "Educación Diferencial (Enseñanza Especial",
          "Educación Preescolar (Educación Parvularia) (Educación Inicial) (Puericultura)(Maestra Jardinera",
          "Educación Primaria(Pedagogía Básica) (Educación Elemental) (Educación Básica) (Maestro Generalista) (Maestro Primaria",
          "Educación Social(Pedagogía Social",
          "Ejército Oficialidad M/Estado Mayor",
          "Ejército Oficialidad M/Ingeniería Militar",
          "Ejército Suboficialidad",
          "Enfermería",
          "Estética(Curador de Arte",
           "Farmacia",
          "Fonoaudiología(Logopedia",
          "Fuerza Aérea Oficialidad M/Operación Aeronaves",
          "Fuerza Aérea Oficialidad M/Administración ",
          "Fuerza Aérea Oficialidad M/Ingeniería ",
          "Fuerza Aérea Oficialidad M/Defensa Aérea ",
          "Fuerza Aérea Suboficialidad ",
          "Gastronomía",
          "Geografía",
          "Geología",
          "Gestión de Organizaciones de la Salud (posttítulo carreras médicas",
          "Gestión y Administración de Ventas",
          "Guía de Turismo",
          "Historia del Arte",
          "Ingeniería Acústica",
          "Ingeniería Aeronáutica(Ingeniería Aeroespacial",
          "Ingeniería Agricultura",
          "Ingeniería Ambiental(Ingeniería Sanitaria y Ambiental) (Química Industrial) (Ingeniería en Calidad Ambiental)(Ingeniería en Saneamiento Ambiental",
          "Ingeniería Biomédica (Bioelectrónica) (Electromedicina) (Ingeniería Biomedicina",
          "Ingeniería Bioquímica(Ingeniería Bioquímica Industrial",
          "Ingeniería de Software(Arquitectura de Software",
          "Ingeniería Electricidad (Ingeniería Eléctrica) (Ingeniería Electrotecnia",
          "Ingeniería Electromecánica",
          "Ingeniería Electrónica",
          "Ingeniería en Acuicultura",
          "Ingeniería en Alimentos",
          "Ingeniería en Computación (Ingeniería en Sistemas Computacionales) (Ingeniería en Control y Cómputo",
          "Ingeniería en Construcción",
          "Ingeniería en Geodesia(Ingeniería Geodésica) (Ingeniero Geodesta",
          "Ingeniería en Geografía",
          "Ingeniería en Topografía(Ingeniería en Geomensura) (Ingeniería en Agrimensura",
          "Ingeniería en Maderas(Ingeniería en Industrias de la Madera) (Ingeniería en Tecnología de la Madera",
          "Ingeniería en Metalurgia(Ingeniería de Materiales",
          "Ingeniería en Minas",
          "Ingeniería en Obras Civiles (Ingeniería en Caminos, Canales y Puertos)(Ingeniería Hidráulica",
          "Ingeniería en Petróleo",
          "Ingeniería en Prevención de Riesgos(Ingeniería en Seguridad y Salud",
          "Ingeniería en Sonido(Ingeniería en Audio",
          "Ingeniería en Telecomunicaciones(Ingeniería en Comunicaciones y Electrónica",
          "Ingeniería en Transporte(Ingeniería de Tráfico",
          "Ingeniería Estadística",
          "Ingeniería Física",
          "Ingeniería Forestal",
          "Ingeniería Genética(Licenciatura en Ciencias Genómicas) (Licenciatura en Biología Molecular",
          "Ingeniería Geofísica(Ingeniería en Geología",
          "Ingeniería Industrial(Ingeniería en Organización Industrial) (Ingeniería en Producción) (Ingeniería de Procesos) (Ingeniería en Procesos de Producción) (Ingeniería en Manufactura) (Ingeniería en Calidad)(Ingeniería de Planta) (Ingeniería en Administración Industrial) (Licenciatura en Administración Industrial",
          "Ingeniería Informática (Ingeniería en Sistemas de Información) (Ingeniería en Tecnologías de Información",
          "Ingeniería Logística",
          "Ingeniería Matemática (Licenciatura en Matemáticas Aplicadas",
          "Ingeniería Mecánica(Ingeniería en Maquinaria Industrial",
          "Ingeniería Mecánica Automotriz(Ingeniería en Automoción",
          "Ingeniería Mecatrónica(Robótica)(Ingeniería Biónica) (Ingeniería Cibernética) (Ingeniería en Control y Automatización) (Ingeniería en Robótica Industrial) (Ingeniería Mecánica Automatización Industrial) (Ingeniería Mecánica en Producción Industrial) (Ingeniería en Instrumentación y Control Industrial)(Biomimética",
          "Ingeniería Multimedia(Informática Gráfica) (Licenciatura de Interacción y Animación Digital",
          "Ingeniería Naval M/Arquitectura Naval",
          "Ingeniería Naval M/Máquinas Marinas",
          "Ingeniería Naval M/Transporte Marítimo",
          "Ingeniería Pesquera",
          "Ingeniería Química(Ingeniería Química Industrial",
          "Ingeniería Refrigeración y Climatización",
          "Ingeniería Telemática (Teleinformática",
          "Ingeniería Textil",
          "Ingeniería Topográfica(Ingeniería Geomática",
          "Interpretación Instrumental",
          "Kinesiología",
          "Licenciatura Administración Agroindustrial",
          "Licenciatura Administración de Aeropuertos(Ingeniería en Aviación Comercial) (Administración Aeronáutica) (Administración Aeroportuaria",
          "Licenciatura Administración de Empresas",
          "Licenciatura Administración en Finanzas",
          "Licenciatura Administración en Recursos Humanos(Relaciones Laborales) (Relaciones Industriales) (Relaciones del Trabajo",
          "Licenciatura Administración en Turismo",
          "Licenciatura Administración Hotelera(Alojamiento",
          "Licenciatura Administración Pública(Administración Gubernamental) (administración Fiscal)(Ciencias Políticas y Administrativas) (Administración y Gestión Pública) (Licenciatura en Ciencias del Gobierno",
          "Licenciatura en Arte M/Dirección Coral",
          "Licenciatura en Arte M/Dirección Orquestal",
          "Licenciatura en Arte M/Sonido(Licenciatura en Música M/Sonido",
          "Licenciatura en Artes Visuales (Bellas Artes) (Licenciatura en Arte)(Licenciatura en Artes Multimediales",
          "Licenciatura en Bioquímica(Biomedicina) (Bioquímica Clínica) (Bacteriología) (Químico Biólogo Clínico",
          "Licenciatura en Cartografía (Geomática",
          "Licenciatura en Ciencias Ambientales(Ingeniería en Recursos Naturales Renovables",
          "Licenciatura en Ciencias de la Computación",
          "Licenciatura en Ciencias de la Familia(Consultor Familiar",
          "Licenciatura en Ciencias Religiosas(Pedagogía en Religión) (Educación Secundaria en Religión) (Profesor en Religión",
          "Licenciatura en Comercialización (Mercadotecnia)(Relaciones Comerciales)(Mercadeo)(Ingeniería de Mercados",
          "Licenciatura en Diseño",
          "Licenciatura en Gestión Ambiental",
          "Licenciatura en Historia",
          "Licenciatura en Lenguas y Literatura (en un idioma extranjero)(Filología)(Licenciatura en Idiomas",
          "Licenciatura en Lenguas y Literatura Hispana( Filología) (Licenciatura en Letras",
          "Licenciatura en Música",
          "Licenciatura en Música M/Canto Lírico",
          "Licenciatura en Música M/Sonido(Licenciatura en Arte M/Sonido",
          "Licenciatura en Óptica(Optometría",
          "Licenciatura en Teología",
          "Licenciatura en Turismo",
          "Lingüística (Lenguas Modernas) (Licenciatura en Letras",
          "Marina Oficialidad M/Navegación ",
          "Marina Oficialidad M/Administración",
          "Marina Oficialidad M/Ingeniería",
          "Marina Oficialidad M/Defensa",
          "Marina Suboficialidad",
          "Marketing",
          "Medicina",
          "Medicina Forense(especialidad de Medicina",
          "Medicina Veterinaria(Producción Animal) (Zootecnia",
          "Meteorología(Ciencias de la Atmósfera",
          "Músico Intérprete",
          "Nutrición y Dietética(Licenciatura en Ciencias Nutricionales",
          "Obstetricia y Puericultura",
          "Oceanografía (Ciencias del Mar",
          "Odontología(Estomatología",
          "Oftalmología (especialidad de Medicina",
          "Orientación  Educativa(Orientación Vocacional)(Orientación Profesional",
          "Paleontología (Especialidad de Geología o Ciencias Biológicas",
          "Paramédico",
          "Pedagogía en Artes Plásticas (Educación Secundaria en Artes Plásticas)(Profesor en Artes Plásticas",
          "Pedagogía en Biología (Educación Secundaria en Biología) (Profesor en Biología",
          "Pedagogía en Contabilidad (Educación Secundaria en Contabilidad) (Profesor en Contabilidad",
          "Pedagogía en Educación Física y Deportes(Educación Secundaria en Educación Física",
          "Pedagogía en Educación Tecnológica (Educación Secundaria en Educación Tecnológica",
          "Pedagogía en Filosofía (Educación Secundaria en Filosofía) (Profesor en Filosofía",
          "Pedagogía en Historia y Geografía (Educación Secundaria en Historia y Geografía",
          "Pedagogía en Lenguaje Español (Educación Secundaria en Lenguaje Español",
          "Pedagogía en Música (Educación Secundaria en Música) (Profesor en Música",
          "Pedagogía en Química (Educación Secundaria en Química) (Profesor en Química",
          "Pedagogía Física (Educación Secundaria en Física)(Profesor en Física",
          "Pedagogía Idioma Extranjero(Educación Secundaria en Idioma Extranjero)(Profesor en Idioma Extranjero",
          "Pedagogía Informática (Educación Secundaria en Informática) (Profesor en Informática",
          "Pedagogía Matemática (Educación Secundaria en Matemática) (Profesor en Matemáticas",
          "Periodismo(Comunicación Social)(Ciencias de la Comunicación) (Comunicación y Medios",
          "Perito Forense(Ciencias Forenses) (Técnico en Ciencias Criminalísticas",
          "Piloto Comercial",
          "Planificación Gestión Educacional (posttítulo de Pedagogía",
          "Policía Oficialidad Administración",
          "Policía Oficialidad Orden y Seguridad",
          "Policía Suboficialidad ",
          "Producción Musical",
          "Programador Analista de Sistemas",
          "Psicología",
          "Psicología",
          "Psicología",
          "Psicología",
          "Psicopedagogía",
          "Psiquiatría",
          "Publicidad(Licenciatura Comunicación y Publicidad) (Comunicación Comercial",
          "Relaciones Internacionales(Licenciatura Estudios Internacionales) (Diplomacia) (Licenciatura en Relaciones Multiculturales",
          "Relaciones Públicas  (Asesor de Imagen)(Imagología",
           "Religiosa",
          "Sacerdocio",
          "Secretariado",
          "Sociología",
          "Teatro (Drama)(Arte Dramático)(Artes Escénicas)(Comunicación Escénica",
          "Técnico Administración Aduanera (Técnico en Comercio Exterior",
          "Técnico Administración en Turismo",
          "Técnico Administración Industrial(Tecnología en Control Industrial) (Tecnología en Control de Calidad",
          "Técnico en Administración de Empresas(Ciencias Empresariales) (Tecnología en Gestión Empresarial",
          "Técnico en Administración de Recursos Humanos(Técnico en Administración de Personal",
          "Técnico en Administración Pública",
          "Técnico en Comercialización",
          "Técnico en Contabilidad (Contador General",
          "Técnico en Deportes(Preparador Físico",
          "Técnico en Minas y Metalurgia(Técnico en Minas) (Técnico Metalúrgico",
          "Técnico en Orientación Familiar",
          "Técnico Jurídico(Asistente Judicial) (Procurador",
          "Técnico Instrumentación Quirúrgica(Arsenalería Quirúrgica",
          "Técnico Agrícola",
          "Tecnología Ambiental",
          "Tecnología Automatización Industrial",
          "Tecnología Comunicación Multimedia(Diseño y Administración Sitios Web) (Diseño Gráfico Multimedial",
          "Tecnología Dental(Protésico Dental",
          "Técnico Diseño Paisajista(Diseño de Jardines y Áreas Verdes",
          "Técnico Diseño Gráfico",
          "Tecnología Electricidad (Electrotecnia",
          "Tecnología Electrónica",
          "Tecnología en Acuicultura",
          "Tecnología en Aduanas(Administración en Aduanas",
          "Tecnología en Computación",
          "Tecnología en Comunicación Audiovisual(Tecnología en Laboratorio de Imagen",
          "Tecnología en Construcción(Obras Públicas",
          "Tecnología en Prevención de Riesgos",
          "Tecnología en Redes y Comunicaciones de Datos",
          "Tecnología en Sonido",
          "Tecnología en Topografía(Técnico Cartográfico)(Técnico Agrimensor",
          "Tecnología en Transporte",
          "Tecnología Forestal",
          "Tecnología Logística",
          "Tecnología Mantenimiento Aeronáutico(Tecnología en Línea de Aviones",
          "Tecnología Mecánica Industrial(Tecnología Mantenimiento Industrial M/Mecánica",
          "Herramientas)",
          "Tecnología Mecánica Automotriz(Tecnología en Automotores)(Tecnología en Mecánica Liviana",
          "Tecnología Mecatrónica(Tecnología en Automatización Industrial",
          "Tecnología Médica Mención Laboratorio Clínico, *Hematología  y Banco de Sangre.(Tecnología de Laboratorio en Análisis Clínicos",
          "Tecnología Médica Mención Morfofisiopatología y Citodiagnóstico",
          "Tecnología Médica Mención Oftalmología",
          "Tecnología Médica Mención *Otorrinolaringología",
          "Tecnología Médica Mención Radiología y Física Médica(Licenciatura en Radiología e Imagen) (Licenciatura en Bioimágenes) (Tecnología Radiológica",
          "Tecnología Óptica",
          "Tecnología Pesquera",
          "Tecnología Química(Tecnología Química Industrial",
          "Teoría de la Música",
          "Terapia Ocupacional (Fisioterapia)(Terapia Física)(Licenciatura en Ciencias de la Ocupación Humana",
          "Trabajo Social (Servicio Social) (Asistente Social) (Licenciatura en Minoridad y Familia",
          "Traductor e Intérprete(Licenciatura en Idiomas)(Traductorado Público)(Licenciatura en Ciencias Lingüísticas",
          "Urbanismo"
        ])
      }, 1000);
    })
  }

}
